In [5]:
import numpy as np
from sklearn.preprocessing import StandardScaler


np.random.seed(0)  # for same results every run

# Generate dataset with 250 students and 5 subjects
# Mean marks around 75, with some variation
X = np.random.normal(loc=75, scale=10, size=(250, 5))

# Keep marks in realistic range (40–100)
X = np.clip(X, 40, 100)

print("Original Dataset Shape:", X.shape)
print("First 5 Rows:\n", X[:5])

X_std = StandardScaler().fit_transform(X)
print("\nStandardized Data:\n", X_std)

cov_matrix = np.cov(X_std.T)
print("\nCovariance Matrix:\n", cov_matrix)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]
print("\nSorted Eigenvalues:\n", eigenvalues)
print("\nSorted Eigenvectors:\n", eigenvectors)

k = 1
principal_components = eigenvectors[:, :k]
print("\nPrincipal Component Matrix:\n", principal_components)

X_reduced = np.dot(X_std, principal_components)
print("\nReduced Dataset (After PCA):\n", X_reduced)

variance_ratio = eigenvalues / np.sum(eigenvalues)
print("\nVariance Percentage:\n", variance_ratio * 100)


Original Dataset Shape: (250, 5)
First 5 Rows:
 [[92.64052346 79.00157208 84.78737984 97.40893199 93.6755799 ]
 [65.2272212  84.50088418 73.48642792 73.96781148 79.10598502]
 [76.44043571 89.54273507 82.61037725 76.21675016 79.43863233]
 [78.33674327 89.94079073 72.94841736 78.13067702 66.45904261]
 [49.47010184 81.53618595 83.64436199 67.5783498  97.69754624]]

Standardized Data:
 [[ 1.82619917  0.47174848  1.03382314  2.21376232  1.87859955]
 [-0.90743012  1.07787361 -0.15329877 -0.06486164  0.37994284]
 [ 0.21074132  1.63357813  0.80513732  0.15374931  0.41415958]
 ...
 [-1.51113717  1.08941216  0.24293302 -0.4986735  -1.17241782]
 [ 2.38138265  0.15975742  0.56685417  0.34447782  0.40484515]
 [ 0.60567962  0.83796748 -0.38846061 -0.24802075 -1.83325646]]

Covariance Matrix:
 [[ 1.00401606 -0.00836329 -0.04603681  0.06029981 -0.02303641]
 [-0.00836329  1.00401606 -0.07349934  0.02165373  0.0722579 ]
 [-0.04603681 -0.07349934  1.00401606 -0.0045982  -0.00792514]
 [ 0.06029981  0.0216